# fly.toml app configuration file generated for conffomo-summer-tree-8549 on 2024-09-04T21:21:21-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'conffomo-summer-tree-8549'
primary_region = 'atl'

[build]

[deploy]
  release_command = '.fly/release.sh'

[env]
  MIGRATE_ON_BOOT = 'true'
  PORT = '8910'
  REDWOOD_DISABLE_TELEMETRY = '1'

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 8910
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
