-- DropForeignKey
ALTER TABLE "Post" DROP CONSTRAINT "Post_PlanId_fkey";

-- AlterTable
ALTER TABLE "Post" ALTER COLUMN "PlanId" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "Post" ADD CONSTRAINT "Post_PlanId_fkey" FOREIGN KEY ("PlanId") REFERENCES "Plan"("id") ON DELETE SET NULL ON UPDATE CASCADE;
